services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "25000:25000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "25001:25001"
    depends_on:
      - backend

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local